### PR TITLE
KungFuFurby's Soundtrack Contribution for unnamed-snes-game

### PR DESCRIPTION
**Pull request by KungFuFurby**
This is my soundtrack contribution for unnamed-snes-game. Any other additional tracks may appear here later on.

### CODE REVIEW

**Comment by undisbeliever** [comment]
Oh wow.  This sounds great.
Thank you for writing music for my game, I really appreciate it.

Before I merge this, could you please let me know what kind of attribution you would like in the credits.

Also, could you please clarify what kind of license/restrictions you release this music under. Preferably with the `#Copyright` and/or `#License` metadata so other people can easily see them in the files.  I'm fine with a no-modifications or *only for use in unnamed-snes-game* restriction. (I just want to know in advance before I merge it.)

**Comment by KungFuFurby** [comment]
I ultimately chose CC BY-SA 4.0. I did this for a few reasons:
- The project in question is open source and is an example project for the unnamed-snes-engine. I kept the attribution and sharealike part for the music, the former for crediting reasons.
- The samples used are from a sample pack that are considered public domain, namely https://github.com/nesdoug/SNES_13/blob/master/MUSIC/More_Samples/NOTES.txt . I did this mostly for example-related reasons... but also because sometimes using my usual samples may accidentally make things a bit more murky outside the scope of the original project.

As for the kind of attribution? Generally my username under Music.

**Comment by undisbeliever** [comment]
Thank you for creating music for my game.

Here are the credits I'm currently using in unnamed-snes-game.  Please let me know if there's any changes you would like me to make.

credits

**Comment by KungFuFurby** [comment]
That works for me!

**Pull request merged**
